Update quickstart.asciidoc
java.io.IOException: failed to obtain lock on /usr/share/elasticsearch/data/   
ECK failing with above error on installation step because of permission issue , and thus updating permission on Elasticsearch init filesystem